### ISSUE TITLE
naming-convention error for React Functional Components

### ISSUE THREAD

**Issue by hankolsen** [iamturns/eslint-config-airbnb-typescript#101]
Hi!
I just upgraded to v8.0.0 and I have problems with  @typescript-eslint/naming-convention and React Functional Components.

Say I have something like this:
```typescript
const MyComponent = (props: Props) => {...}
```

However that results in:
```
Variable name MyComponent must match one of the following formats: camelCase, UPPER_CASE        @typescript-eslint/naming-convention
```

Is this a bug or a feature? :)

**Comment by hankolsen** [comment]
Thanks for the quick turnaround!

I noticed two other issues after upgrading:
* "UNSAFE_componentWillReceiveProps" is marked as error
* It is not allowed to use _ as an "ignored" parameter in a function callback, like for instance
```typescript
 something.then((_, err) => {...})
```

**Comment by iamturns** [comment]
Sorry about that @hankolsen - still adjusting to this new rule provided by `@typescript-eslint`

Let me know if you find anything else 🙏

**Comment by hankolsen** [comment]
Thank you @iamturns !
