### ISSUE TITLE
How to enable recommended rules?

### ISSUE THREAD

**Issue by loginov-rocks** [iamturns/eslint-config-airbnb-typescript#11]
Hi!

Could you please explain how to enable and mix recommended rules, like:
* eslint/recommended
* typescript-eslint/recommended
* airbnb

I tried the following:
```
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "airbnb-typescript"
  ],
```

This looks like working, is it the correct way?

Thanks!

**Comment by iamturns** [comment]
Yep, that looks great!

Here's the [ESLint config I use](https://github.com/iamturns/create-exposed-app/blob/master/examples/default-client-side/.eslintrc.js), with a combination of a few other plugins and Prettier

**Comment by loginov-rocks** [comment]
I believe order matters here, in your example `airbnb-typescript` goes before `plugin:@typescript-eslint/recommended` - does not one's overlap others?
