### ISSUE TITLE
Error in .eslintrc

### ISSUE THREAD

**Issue by jamesmichaelkuizon** [iamturns/eslint-config-airbnb-typescript#110]
I got this error in my `.eslintrc`:
``` 
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.
```
After adding this package. Here is a copy of my `.eslintrc`:
```
module.exports = {
    parser: "@typescript-eslint/parser",
    env: {
      browser: true,
      es2020: true
    },
    extends: [
      'airbnb-typescript',
      'plugin:react/recommended',
      'plugin:@typescript-eslint/recommended',
      'prettier/@typescript-eslint',
      'plugin:import/typescript',
      'prettier',
      'prettier/react',
      'plugin:prettier/recommended'
    ],
    parserOptions: {
      project: './tsconfig.json',
    },
    plugins: ['react', '@typescript-eslint'],
    rules: {
      'no-console': 2,
      'comma-dangle': ['error', 'never'],
      'import/no-unresolved': [2, { commonjs: true }],
      'import/extensions': [
        'error',
        'ignorePackages',
        { ts: 'never', tsx: 'never' }
      ],
      "@typescript-eslint/explicit-module-boundary-types": "off"
    }
  };
  ```

Please help me. Thanks.

**Comment by ixahmedxi** [comment]
I had this error before and I solved it by adding `**/*.js` to the includes in the tsconfig.json. If you do not want to lint JS files at all just add `**/*.js` in the .eslintignore file and the error will be gone.

**Comment by jamesmichaelkuizon** [comment]
Thanks @ixahmedxi . It worked.

**Comment by xstable** [comment]
@ixahmedxi do you have a hint for me? 
Your adjustment with `**/*.js` doesn't work for me. 

But if I add `.eslintrc.js` to `tsconfig.js` file, the error is gone _for this file_.
I've tried the same with jest.config.js, but there it doesn't work.
![image](https://user-images.githubusercontent.com/1778068/92578150-c8b67c80-f28b-11ea-9fe3-a45ebc261c8b.png)

Hope you can give me a hint to solve that.
