### ISSUE TITLE
eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by zprjk** [iamturns/eslint-config-airbnb-typescript#112]
Hello.

README.md states that we need to install some dependencies including `eslint-plugin-react-hooks` v2.X

Currently `eslint-config-airbnb` supports `eslint-plugin-react-hooks` v4:
https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v18.2.0/packages/eslint-config-airbnb/package.json#L71.

Are we safe to use `eslint-plugin-react-hooks` latest version ?

Thanks.

**Comment by iamturns** [comment]
Hey @zprjk - I've just updated all dependencies, including updating to `eslint-plugin-react-hooks` v4. Cheers!
