### ISSUE TITLE
Feature request: expand airbnb's list of files for `import/no-extraneous-dependencies` to include TS files

### ISSUE THREAD

**Issue by Martyniuk** [iamturns/eslint-config-airbnb-typescript#121]
When importing packages into config files written in TS (eg, `webpack.config.ts`), an error will be reported claiming `webpack` should be a dependency, not a dev dependency

<img width="500" alt="Screenshot 2020-08-03 at 16 50 01" src="https://user-images.githubusercontent.com/12961943/89190002-7eb1eb00-d5a9-11ea-86d9-d1302b5ec5b7.png">

In the spirit of [airbnb's config for `import/no-extraneous-dependencies`](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L71), it would be great for `eslint-config-airbnb-typescript` to extend that list to also include TS files.

version of:
`"eslint-config-airbnb-typescript": "^8.0.2",`

**Comment by aryzing** [comment]
That would be amazing, I need this too. Ran into this issue myself today.

**Comment by Martyniuk** [comment]
I've already have this support, possibly there is some mistake from my side. Gonna close it for now.

![Screenshot 2020-08-05 at 10 20 42](https://user-images.githubusercontent.com/12961943/89383647-84244800-d705-11ea-9272-2e3a9473ddef.png)
