### ISSUE TITLE
Add eslint-import-resolver-typescript as a dependency

### ISSUE THREAD

**Issue by alex-e-leon** [iamturns/eslint-config-airbnb-typescript#125]
This would allow for better out of the box support for adjusting `baseUrl` or path aliases in tsconfig

**Comment by iamturns** [comment]
This resolver looks like a nice enhancement, but doesn't seem critical to supporting the airbnb rules. The intention of this library is simply to add TypeScript support to the airbnb config. This resolver could optionally be installed by the consumer if needed. What do you think?

**Comment by alex-e-leon** [comment]
@iamturns you're correct but adding eslint-import-resolver-typescript would lead to better out of the box support for TS, and complements @typescript/eslint-parser - it's up to you whether you prefer to include this or not though.

**Comment by kripod** [comment]
I think that [extending configs from `plugin:import/typescript`](https://github.com/benmosher/eslint-plugin-import#typescript) would be a better choice. It's an official [method](https://github.com/benmosher/eslint-plugin-import/blob/master/config/typescript.js) which could serve as a replacement (or at least an improvement) for the code snippets below:

- https://github.com/iamturns/eslint-config-airbnb-typescript/blob/1d01455c0ca716288e42337103274446f70228d7/index.js#L5-L12
- https://github.com/iamturns/eslint-config-airbnb-typescript/blob/533bdf7b79c54acb93641afb1f8af7dd5e88f97a/lib/shared.js#L12-L23
