### ISSUE TITLE
"comma-dangle" rule broken with enums

### ISSUE THREAD

**Issue by Zamiell** [iamturns/eslint-config-airbnb-typescript#147]
1) Airbnb specifies in rule `20.2` of the style guide that we should use dangling commas.

2) This is expressed in the ESLint config here:
https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L54-L57
```
    // require trailing commas in multiline object literals
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline',
    }],
```

For reference, the documentation for the `comma-dangle` rule is documented here:
https://github.com/eslint/eslint/blob/master/docs/rules/comma-dangle.md#options

As we can see, the Airbnb config specifies "always-multiline" for all 5 object options.

3) This repository extends the base config here:
https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L54-L57
```
    // Replace Airbnb 'comma-dangle' rule with '@typescript-eslint' version
    // https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/comma-dangle.md
    'comma-dangle': 'off',
    '@typescript-eslint/comma-dangle': baseStyleRules['comma-dangle'],
```

For reference, the documentation for the `@typescript-eslint/comma-dangle` rule is located here:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/comma-dangle.md

As we can see, the TypeScript version of the rule adds 3 new object options: `enums`, `generics`, and `tuples`.

**However, this repository does not specify "always-multiline" for these 3 new object options.** This is a bug, as it should almost certainly do so. For example, this bug results in the following code:

```
enum foo {
  thing1: string,
  thing2: string,
  thing3: string,
}
```

being automatically fixed (by `eslint --fix`) to this:

```
enum foo {
  thing1: string,
  thing2: string,
  thing3: string
}
```

To fix this bug, this repository could replace the above code snippet with the following code:

```
    // Replace Airbnb 'comma-dangle' rule with '@typescript-eslint' version
    // https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/comma-dangle.md
    'comma-dangle': 'off',
    '@typescript-eslint/comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline',
      enums: 'always-multiline',
      generics: 'always-multiline',
      tuples: 'always-multiline',
    }],
```

Or perhaps, less explicitly and using the spread operator:

```
    // Replace Airbnb 'comma-dangle' rule with '@typescript-eslint' version
    // https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/comma-dangle.md
    'comma-dangle': 'off',
    '@typescript-eslint/comma-dangle': [baseStyleRules['comma-dangle'][0], {
      ...baseStyleRules['comma-dangle'][1],
      enums: baseStyleRules['comma-dangle'][1].arrays,
      generics: baseStyleRules['comma-dangle'][1].arrays,
      tuples: baseStyleRules['comma-dangle'][1].arrays,
    }],
```

Thank you.

**Comment by iamturns** [comment]
Hey @Zamiell - this is probably the best issue I've ever seen! Thoroughly researched with helpful links. Thank you!

I think the solution you proposed in the last code snippet is great. Would you like to create a PR for it? I feel that you should be recognised as the contributor for this code, as you have already written it :)

**Comment by Zamiell** [comment]
Done.

As an aside, I suspect the reason that no-one else caught this bug is because everyone is using prettier nowadays.
I made the switch and I am liking it a lot.
Although I do use [btmills' fork](https://github.com/btmills/prettier) (to keep in prefix operators, like it says in the Airbnb config).

**Comment by iamturns** [comment]
Thanks @Zamiell 👍
