### ISSUE TITLE
Ruleset suggestions

### ISSUE THREAD

**Issue by deskoh** [iamturns/eslint-config-airbnb-typescript#16]
There are certain ESLint equivalent rules that can be replaced by `@typescript-eslint` equivalent. A good reference can be found in [@typescript-eslint/recommended](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json). They are `no-use-before-define`, `no-empty-function`.

Also certain rules can be turned off for TypeScript files as they would be checked by TypeScript compiler. A good reference would be [@typescript-eslint/eslint-recommended](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts).

**Comment by iamturns** [comment]
Hey @deskoh 

This config was using a slightly older version of `@typescript-eslint` without those rules you mentioned.

Have just updated to the latest version of `@typescript-eslint` in #17. This PR includes the rules you mentioned.

Great catch and very thorough, please let me know if you find any other missing rules now 👍

**Comment by iamturns** [comment]
Good suggestion about disabling rules checked by TSC.

As `eslint-config-airbnb-typescript` is configured to work for both `js` and `ts` files, this would require using the more complex `overrides` syntax, e.g.:

```
overrides: [
  {
    files: ['*.ts', '*.tsx'],
    rules: {
      'example-rule-checked-by-tsc': 'off',
    },
  },
]
```

However this makes it difficult to make local overrides, an issue discovered previously in #4.

I would also prefer to keep `eslint-config-airbnb-typescript` closely mirroring `eslint-config-airbnb`.

You can choose to opt-in to using that config with something like:

```
{
  "extends": [
    "airbnb-typescript",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ]
}
```

**Comment by deskoh** [comment]
> Hey @deskoh
> 
> `eslint-config-airbnb-typescript` was using a slightly older version of `@typescript-eslint`, and those roles did not exist.
> 
> Have just updated to the latest version of `@typescript-eslint` in #17 and added those rules you've mentioned.
> 
> Great catch and very thorough checking, thank you! Please let me know if you find any other missing rules now 👍

Great update!

Consider the following:

* `@typescript/no-extra-parens` is unnecessary? (See commit https://github.com/airbnb/javascript/commit/56a524a47ed0b71f348d6bfaa42289d562f6bc5b for details).

* The same goes for `@typescript/no-magic-numbers` as the rule is disabled.

* `quotes` can be replaced by `@typescript-eslint/quotes`.

I wrote the following script to help catch the above 😄 
https://github.com/deskoh/typescript-eslint-util

**Comment by iamturns** [comment]
Thanks @deskoh !
