### ISSUE TITLE
Don't pin `eslint-config-airbnb-base` dependency version

### ISSUE THREAD

**Issue by maxmilton** [iamturns/eslint-config-airbnb-typescript#249]
> Note: Turning my comment in https://github.com/iamturns/eslint-config-airbnb-typescript/pull/247 into an issue for better visibility.

Since `eslint-config-airbnb-base` is in `dependencies` as of https://github.com/iamturns/eslint-config-airbnb-typescript/commit/50d919058a9a918b1f4e3c6cbd7ccb0e1e1f1dc9, shouldn't the version have a caret (e.g., `^14.2.1`) so future updates for v14 are also installed?

Pinning package dependencies versions is a great strategy for end users wanting a tightly reproducible experience. But for packages like this one which will be consumed by others, it's usually better to give a version range so future package updates will be potentially installed.

Alternatively, maybe `peerDependencies` would be a viable option since package managers notify missing peerDependencies on install.

**Comment by iamturns** [comment]
Yep, good catch @maxmilton  - I didn't give it enough thought at the time

Thanks @zraineri for the PR 👍

**Comment by iamturns** [comment]
Fix is in 14.0.2
