### ISSUE TITLE
Update dependency to support ESLint 8

### ISSUE THREAD

**Issue by doasync** [iamturns/eslint-config-airbnb-typescript#264]
https://github.com/iamturns/eslint-config-airbnb-typescript/blob/2c0baa3660a1b51ab2c46e7dff144c0520649567/package.json#L26

Please update this dependency to support ESLint 8. 

I installed ESLint 8 and have the following warning:
`warning "eslint-config-airbnb-typescript > eslint-config-airbnb-base@14.2.1" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0 || ^7.2.0".`

**Comment by kurone-kito** [comment]
@doasync The case seems to be discussed in the https://github.com/iamturns/eslint-config-airbnb-typescript/issues/251#issuecomment-966077880 .
