### ISSUE TITLE
Replace rules with '@typescript-eslint' version

### ISSUE THREAD

**Issue by shpakkdv** [iamturns/eslint-config-airbnb-typescript#269]
'default-param-last' and 'no-loss-of-precision' have their TypeScript versions:

- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/default-param-last.md
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-loss-of-precision.md

They should be replaced as the latest Airbnb config turned on these rules:
https://github.com/airbnb/javascript/commit/f3d3a075cda2acc02011e71991c10bb5b4a15278#diff-636a5a6c2241413cacff372de09bd7ba4c9fbecf0045fea60aef0490fd9ae7fa

Please consider this Pull Request: https://github.com/iamturns/eslint-config-airbnb-typescript/pull/268/files

**Comment by iamturns** [comment]
Thanks @shpakkdv - great catch on these new rules. I checked the changelog from the latest upgrade, but didn't check the actual code diff 😅 Cheers!
