### ISSUE TITLE
Mismapping of `no-return-await` to `return-await`

### ISSUE THREAD

**Issue by lotap** [iamturns/eslint-config-airbnb-typescript#278]
The value for `no-return-await` from airbnb is being incorrectly mapped to `return-await` (https://typescript-eslint.io/rules/return-await/)

This is effectively linting the opposite of what it should and forcing the code to always add `await` to the return instead of disallowing it.

Recommend switching to `@typescript-eslint/return-await': [baseBestPracticesRules['no-return-await'], 'never'],` for parity with the airbnb base config

**Comment by iamturns** [comment]
Great catch @lotap !

Did you want to create a PR for it? You've done the work and provided the code too, I think you should get the cred!

**Comment by lotap** [comment]
Created https://github.com/iamturns/eslint-config-airbnb-typescript/pull/279 lmk if there are any issues, I think this is my first opensource PR

**Comment by iamturns** [comment]
Nice one @lotap ! Released in v16.1.1
