### ISSUE TITLE
prefer-const doesn't seem to be used 

### ISSUE THREAD

**Issue by DominicGBauer** [iamturns/eslint-config-airbnb-typescript#313]
Looking at https://github.com/airbnb/javascript#references--prefer-const it looks like `prefer-const` is part of the air bnb style guide but doesn't seem to be part of this config.

I would like it to be, can we add it?

**Comment by iamturns** [comment]
Is there an equivalent TypeScript ESLint rule for `prefer-const`? I did a quick search and can't see it. So I'm not sure what change would be added to this config. Feel free to make a PR!

**Comment by DominicGBauer** [comment]
@iamturns Oh man I'm so sorry I thought this was meant to have types from airbnb as well but this is actually just to enhance it.
