### ISSUE TITLE
Is this repo still maintained? 

### ISSUE THREAD

**Issue by DominicGBauer** [iamturns/eslint-config-airbnb-typescript#314]
Looks like this isn't being maintained anymore?

**Comment by JenieX** [comment]
Came to ask this as well.

**Comment by iamturns** [comment]
Sorry, it hasn't been maintained for quite a while. Life has become busy for me. I don't think any huge maintenance is required beyond keeping dependencies updated. PRs welcome!

**Comment by JenieX** [comment]
> Sorry, it hasn't been maintained for quite a while. Life has become busy for me. I don't think any huge maintenance is required beyond keeping dependencies updated. PRs welcome!

I testing it since yesterday, everything seems fine. Thank you for this project.
