### ISSUE TITLE
need to update dependencies

### ISSUE THREAD

**Issue by ianzone** [iamturns/eslint-config-airbnb-typescript#324]
WARN  Issues with peer dependencies found
.
├─┬ eslint-config-airbnb-typescript 17.0.0
│ ├── ✕ unmet peer @typescript-eslint/eslint-plugin@^5.13.0: found 6.0.0
│ └── ✕ unmet peer @typescript-eslint/parser@^5.0.0: found 6.0.0

**Comment by dartess** [comment]
I'll try to make a PR for this today.

**Comment by abdulramonjemil** [comment]
I'm also running into this issue. I want to update but am unable to due to dependency issues.

**Comment by abdulramonjemil** [comment]
Maybe tagging @iamturns would help.
