### ISSUE TITLE
'React' is defined but never used  @typescript-eslint/no-unused-vars

### ISSUE THREAD

**Issue by artem-gorokhovskii** [iamturns/eslint-config-airbnb-typescript#42]
Hello everyone!
I have met the problem with .tsx files:
`'React' is defined but never used  @typescript-eslint/no-unused-vars`.

I have the only record in .eslintrc.json: 
`{ "extends": ["airbnb-typescript"] }`

Could you help, how to resolve this problem?

I can resolve this problem with setting for `"@typescript-eslint/no-unused-vars"` next value:
`"varsIgnorePattern": "React"`
but it is not very correct.

Thank you!

**Comment by iamturns** [comment]
Hey @artem-gorokhovskii 

I can't replicate this one.

Does your `tsx` file look something like this?

```
import * as React from 'react';
```

Are you running the latest versions of `eslint-*` and `@typescript-eslint/*` packages?

**Comment by artem-gorokhovskii** [comment]
Hi, @iamturns,
Yes, I have string such your string.

My versions were:
```
"@typescript-eslint/eslint-plugin": "2.3.0",
"eslint": "6.6.0",
"eslint-config-airbnb-typescript": "6.1.0",
"eslint-plugin-import": "2.18.2",
"eslint-plugin-jsx-a11y": "6.2.3",
"eslint-plugin-react": "7.14.3",
"eslint-plugin-react-hooks": "1.7.0",
```

After updating some packages:
```
"@typescript-eslint/eslint-plugin": "2.7.0",
"eslint-plugin-react": "7.16.0",
"eslint-plugin-react-hooks": "2.2.0",
```
I still have the same error.

UPD:
I had the error in file, where I used only `ReactDOM.render` without any `jsx` code and here imporing React is really useless action and linter is correct.
Thank you!

**Comment by iamturns** [comment]
Cool, good to hear the linter finding hard-to-detect issues! 👍
