### ISSUE TITLE
no-dupe-class-members error

### ISSUE THREAD

**Issue by snacqs** [iamturns/eslint-config-airbnb-typescript#61]
Hey 👋

As you know it's possible to overload functions and methods in TypeScript.

I receive `no-dupe-class-members` error when I try to overload class method:
```ts
class Foo {
  bar(arg0: string): void;
  bar(arg0: string, arg1: string): void;
  bar(arg0: string, arg1?: string) {
    // implementation
  }
}
```

Also TypeScript throws an error if we have duplicate identifiers in our code:
```ts
// Duplicate identifier 'bar'.
class Foo {
  bar = 1;
  bar = 1;
}

// Duplicate identifier 'bar'.
class Foo {
  get bar() {
    return 1;
  }
  get bar() {
    return 1;
  }
}
```

Maybe this rule can be disabled? Or there might be some unexpected consequences 🤔

Here are some links that might be useful:
- [ESLint `no-dupe-class-members` rule](https://eslint.org/docs/rules/no-dupe-class-members)
- [Rule in Airbnb config](https://github.com/airbnb/javascript/blob/8148bfce3c670a8a234ee71903ca020e32506884/packages/eslint-config-airbnb-base/rules/es6.js#L52)

**Comment by snacqs** [comment]
@iamturns wdyt?

**Comment by iamturns** [comment]
Hey @snacqs - thanks for the issue and PR! Very well written, I appreciate it all the info 👍
Rule is disabled now in `6.3.2` 🎉
