### ISSUE TITLE
7.0.0 tsconfig errors (The file must be included) & (File not found)

### ISSUE THREAD

**Issue by viT-1** [iamturns/eslint-config-airbnb-typescript#68]
When I migrate to v7.0.0 with linting in package.json scripts such as:
`tsc --project ./src/tsconfig.dev.json --noEmit && eslint **/*.{ts,json,js} *.* .*.js`
& [eslintrc](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ee664ec48aa390feaa29fd53a142911810ccfa20/.eslintrc.js) config with
```
parserOptions: {
	project: './src/tsconfig.dev.json',
	extraFileExtensions: ['.json'],
},
```

have a list of errors (package.json & even *.spec files!):
```
C:\Projects\systemjs-ts-es6-vue\src\tsconfig.dev.json
  0:0  error  Parsing error: File 'c:\projects\systemjs-ts-es6-vue\src\tsconfig.dev.json' not found

C:\Projects\systemjs-ts-es6-vue\package-lock.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: package-lock.json.
The file must be included in at least one of the projects provided

C:\Projects\systemjs-ts-es6-vue\package.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: package.json.
The file must be included in at least one of the projects provided
```

[Test project](https://github.com/viT-1/systemjs-ts-es6-vue) before migrating

**Comment by viT-1** [comment]
With v6.3.1 lint is working without these errors.

**Comment by iamturns** [comment]
It looks like you are trying to lint `.json` files with ESLint.

Have you added a JSON file parser to ESLint?
Perhaps there is a clash between the two ESLint parsers (one for TS, and one for JSON).

If you provide the part of your ESLint config file that parses `.json` files, then might be able to figure out the problem.

**Comment by viT-1** [comment]
@iamturns 
> Have you added a JSON file parser to ESLint?

Yes. eslint-plugin-json v2.0.1 [in package.json](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ee664ec48aa390feaa29fd53a142911810ccfa20/package.json#L77) is configured [in eslinrc](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ee664ec48aa390feaa29fd53a142911810ccfa20/.eslintrc.js#L36)

**Comment by viT-1** [comment]
Oops! I [rewriting json](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ee664ec48aa390feaa29fd53a142911810ccfa20/.eslintrc.js#L39) configuration (copy-paste problem).
Jus trying again

**Comment by viT-1** [comment]
Yes eslint [configuration for json files](https://github.com/viT-1/systemjs-ts-es6-vue/blob/f7f0d959611710b0f9ec949e74b1fba5dce12fb4/.eslintrc.js#L35) is ok now, but migrating to 7.0.0 fired those errors.

**Comment by viT-1** [comment]
My use case:
I need to lint all files (even in project root), buttsconfig files in my project used only for tsc bundling (without including project root files). And why I should include all root files for linting in tsconfig (e.g. tsconfig.lint.json extends tsconfig.dev.json)?

**Comment by ulrik59** [comment]
I have the same problem. We have a `cypress/` folder and a `src/` folder. The `tsconfig.json` is configure to only include files in `src/` folder but my eslint is configured to run on both folders.
This is resulting in a lot of errors of this kind:
```
/home/[...]/cypress/support/index.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: cypress/support/index.js.
The file must be included in at least one of the projects provided

```

**Comment by iamturns** [comment]
Hey @viT-1 and @ulrik59 ,

I found this issue within `typescript-eslint`:
https://github.com/typescript-eslint/typescript-eslint/issues/890

It seems the `tsconfig.json` file set within ESLint config must include _all_ files that ESLint lints.

The issue contains an example solution to create a `tsconfig.eslint.json` file, which extends `tsconfig.json`, and adds any additional includes requires to satisfy ESLint.

Let me know if this helps

**Comment by viT-1** [comment]
@iamturns All these errors not related to 7.0 version
but tsconfig with adding `parserOptions` section (tested with eslint-config-airbnb-typescript 6.3.1)

Only [this comment](https://github.com/typescript-eslint/typescript-eslint/issues/967#issuecomment-538899503) helps me to avoid many errors, but link on tsconfig file (which is configured in parserOption) still raise error:
```
C:\Projects\systemjs-ts-es6-vue\src\tsconfig.lint.json
  0:0  error  Parsing error: File 'c:\projects\systemjs-ts-es6-vue\src\tsconfig.lint.json' not found
```

My folder named `Projects` not `projects` =(
Win10

**Comment by viT-1** [comment]
But now (with parserOptions) linting is veeeeery slow =(
