### ISSUE TITLE
Shared eslint-config in monorepo

### ISSUE THREAD

**Issue by alfechner** [iamturns/eslint-config-airbnb-typescript#71]
I updated to `7.0.0`. We have a monorepo structure as follows:

```
eslint-config
eslint-config/.eslintrc.js
package-a
package-a/tsconfig-a.json
package-b
package-b/tsconfig-b.json
```

The packages `package-a` and `package-a` both consume `.eslintrc.js` from the shared `eslint-config` package. But both packages use different TypeScript configuration files.

I struggle with configuring the `parserOptions.project` option (see #63) in a way, that each package uses it's dedicated `tsconfig` file. Any ideas?

**Comment by iamturns** [comment]
Hey @alfechner

Here's some recommendations:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md

**Comment by alfechner** [comment]
@iamturns  I couldn't make it work.

We have a shared eslint config package. This setup is different from the one described in the [docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md). They assume the mono repository has a global eslint file.

We have a structure like this:

```
shared-eslint-config
 |_ .eslintrc.js
package-a
 |_ .eslintrc.js
package-b
 |_ .eslintrc.js
```

The `.eslintrc.js` of `pacakge-a` and `package-b` both extend the configuration in `shared-eslint-config`.

If I configure the parser in `shared-eslint-config``it works for this package only. If I try to override the parser options in the `.eslintrc.js` files of  `pacakge-a` and `package-b` I see an error saying the parser options have been set.

Could we reopen the issue please?

**Comment by iamturns** [comment]
Hey @alfechner , I recommend raising the issue within [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/). That is source of the requirement for `parserOptions.project`. Good luck!

**Comment by alfechner** [comment]
Thanks @iamturns, I opened this [issue](https://github.com/typescript-eslint/typescript-eslint/issues/1681).
