### ISSUE TITLE
Connect airbnb reports to sonar

### ISSUE THREAD

**Issue by Hanzofm** [iamturns/eslint-config-airbnb-typescript#75]
Hi,

Previously I have been using tslint-config-airbnb and in my sonar-properties file had this config:

```
...
sonar.exclusions=**/node_modules/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.typescript.tslint.reportPaths=tslint-report.json
```

On my package.json I had this run script:

`  "sonar-tslint": "npm run tslint:json || npm run sonar"`

Now tslint are deprecated and use this packages:

```
     eslint-config-airbnb": "^18.0.1",
    "eslint-config-airbnb-typescript": "^6.3.1",
    "eslint-config-prettier"
```

And my sonar file looks like this:

```
...
sonar.exclusions=**/node_modules/**
sonar.typescript.tsconfigPath=tsconfig.json
```

What would be a valid configuration to integrate eslint config airbnb typescript with sonar?

Thanks

**Comment by iamturns** [comment]
Sorry @Hanzofm I've never heard of Sonar. You're likely to get better support asking Sonar. Good luck!
