### ISSUE TITLE
Airbnb-typescript creates syntax error when linting react HOC with generics in --fix mode

### ISSUE THREAD

**Issue by sergesemashko** [iamturns/eslint-config-airbnb-typescript#8]
I've encountered a really interesting issue using airbnb-typescript config with --fix flag.

For some reason, airbnb-typescript eslint config doesn't like react higher order components with generics and tries to wrap generic opening tag character with parenthesis.

So, following code: 
```tsx
const HOCFails = <P extends object>(
  Component: React.ComponentType<P>,
): React.ComponentType<P> => {
  const withFClass = (props: P) => <Component {...props as P} />;
  return withFClass;
};
```
becomes:
```tsx
const HOCFails = (<)P extends object>(
  Component: React.ComponentType<P>,
): React.ComponentType<P> => {
  const withFClass = (props: P) => <Component {...props as P} />;
  return withFClass;
};
```

and eslint exists with:
`error  Parsing error: Expression expected`

However, it works on custom eslint + prettier + eslint-typescript setup.

I created a repo to reproduce the issue with both failing and passing configs:
https://github.com/sergesemashko/airbnb-typescript-eslint-test

I'm really out of guesses at this point and looking for any troubleshooting tips as I would like to keep using airbnb-typescript

**Comment by iamturns** [comment]
Hey @sergesemashko 

Thanks for the very detailed bug report and test repo, it really helped to narrow down the issue.

The problem lies within the `arrow-parens` rule.

Here is the fix: https://github.com/iamturns/eslint-config-airbnb-typescript/commit/bca94c45b5f66481820e486d1081ad4399a34ebe

🎉 Released on npm as v4.0.0

**Comment by deskoh** [comment]
@iamturns Seems like this is no longer an issue with latest library. Verified it using PR sergesemashko/airbnb-typescript-eslint-test#1

**Comment by deskoh** [comment]
Turns out this was no longer the issue because `airbnb` v18 and `airbnb-base` v14 `arrow-parens` rule no longer have `requireForBlockBody` option. See https://github.com/typescript-eslint/typescript-eslint/issues/14#issuecomment-500604282 for more info.
