### ISSUE TITLE
Upgrade to use typescript-eslint v3.0.0

### ISSUE THREAD

**Issue by branflaker** [iamturns/eslint-config-airbnb-typescript#95]
The latest version of typescript-eslint (v3.0.0) [was released earlier today](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0).  It has a few breaking changes that affect this config.
Specifically, running with v3.0.0, the `camelcase` is no longer recognized and has been replaced by the `naming-convention` rule.

**Comment by iamturns** [comment]
Thanks for the heads up! I'll do a big dependency update soon, along with ESLint version 7. Just waiting for this to be released: https://github.com/airbnb/javascript/issues/2223

**Comment by bbeesley** [comment]
Created a PR to replace the camelcase ref since this is backing up our repos with dependabot PRs.

**Comment by iamturns** [comment]
Fixed in #99 and released as v8.0.0 🎉
